unset(CMAKE_XCODE_ATTRIBUTE_INSTALL_PATH)

set(MACOSX_BUNDLE_GUI_IDENTIFIER "in.ioshack")
set(CMAKE_MACOSX_BUNDLE YES)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "NO")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "")
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")

set(CMAKE_OSX_SYSROOT iphoneos)
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS macosx)
set(CMAKE_XCODE_EFFECTIVE_PLATFORMS "-iphonesimulator")
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTS_MACCATALYST "YES")

set(CMAKE_CXX_FLAGS "-std=c++11 -Wno-shorten-64-to-32")
